### ISSUE TITLE
Does not Render with Slate Global Invalidation

### ISSUE THREAD

**Issue by mhughson** [SourySK/NiagaraUIRenderer#1]
With Slate Global Invalidation enabled, NiagaraWidgets do not properly render. They are being cached and never "invalidated" and they are not volatile. I don't know very much about the Niagara rendering system, but it seems likely that these widgets should just be marked volatile.

Note: This cannot be reproduced in the "Selected Viewport" mode, as that seems to have Global Invalidation disabled always. You need to run the game in a "New Editor Window (PIE)" and ensure that global invalidation is enabled (can be done via console command: Slate.EnableGlobalInvalidation 1)

I was seeing this is on UE5 Preview, and have not tested if UE4 is any different.

**Comment by SourySK** [comment]
Hi! Thank you for the suggestion. I'll mark the Niagara System Widgets as Volatile by default.
