### ISSUE TITLE
Update for Unreal 5.1

### ISSUE THREAD

**Issue by dapetcu21** [SourySK/NiagaraUIRenderer#12]
There are currently a bunch of compilation issues on 5.1

**Comment by SourySK** [comment]
Hi, did you grab the latest, because I've pushed the update to 5.1 yesterday and there are no compilation issues there.

**Comment by dapetcu21** [comment]
Sorry. I might not be on the latest, my bad. I looked on main and didn't see a commit since august and assumed nothing changed, but forgot to check the UE5 branch.

**Comment by SourySK** [comment]
No worries, I've merged the UE5 version into main and created a separate branch for UE4 to avoid future confusion for other people.
