### ISSUE TITLE
Compile Error in UE4.25.4

### ISSUE THREAD

**Issue by xieyxpro** [SourySK/NiagaraUIRenderer#2]
Compile Error in UE4.25.4

**Comment by SourySK** [comment]
Hi! Can you be more specific about the error? I've built the plugin for 4.26, which is also the official supported version. It is possible that you'll need to make some modifications to the plugin for earlier UE4 versions in order to get it working.

**Comment by SourySK** [comment]
I've tried compiling it for 4.25 and it looks like the main problem is that there aren't attribute readers for Niagara systems in UE4.25, which is the way I'm getting the data from the particle system. It should be theoretically fixable, but you'll need to modify the plugin heavily, and find some other way to get the data from the Niagara systems. If you really need this plugin, I would recommend upgrading your project to UE4.26. I'm sorry that I cannot help, but even if it's possible, it would require a lot of work to get this running on the older engine versions. For this reason I don't plan to support anything below 4.26.
