### ISSUE TITLE
Color Error in Ribbon ParticleSystem

### ISSUE THREAD

**Issue by NeverStopMata** [SourySK/NiagaraUIRenderer#3]
When a color curve is used in Niagara particle system, we just see the wrong color caused by a little mistake in NiagaraUIComponent.cpp(line 424).
![image](https://user-images.githubusercontent.com/20719573/123931638-45ede200-d9c3-11eb-9315-30c0033b2704.png)
Pls use **CurrentDataIndex** instead to make the color right.

**Comment by SourySK** [comment]
Thank you for catching that. I'm going to fix that right away.
