### ISSUE TITLE
Does not Compile in 5.1 (Not Really an Issue, just a request)

### ISSUE THREAD

**Issue by jessy5765** [SourySK/NiagaraUIRenderer#6]
There are a few issues with trying to compile in 5.1. This is the only plugin at this point were having issues with you trying to go to 5.1. Might you have already tested this and possibly have a fix? :D 

If not, may I request of you, given you have some free time to do so, update this to 5.1 please? 

Thank you,
Darinius

**Comment by jessy5765** [comment]
![image](https://user-images.githubusercontent.com/18355713/147429218-f82b5fed-6426-476c-af2e-5fe05475e021.png)

Here is an image of the errors btw. Not sure if that could do anything to help if its a quick fix.

**Comment by SourySK** [comment]
Thanks for letting me know. This should be already fixed in the new branch for 5.1. I haven't had time to test all the features in 5.1. and since it's a development version please use with caution and be aware that there might be some more bugs in there.
